### ISSUE TITLE
import-a:world problem 

### ISSUE THREAD

**Issue by musdinc** [NetLogo/ImportA-Extension#5]
I am getting the following error using the command import-a:world 

NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 

java.lang.IllegalArgumentException: requirement failed: not event thread: Thread[JobThread,4,main]
 at scala.Predef$.require(Predef.scala:281)
 at org.nlogo.awt.EventQueue$.mustBeEventDispatchThread(EventQueue.scala:23)
 at org.nlogo.window.GUIWorkspaceScala$$anon$1.showError(GUIWorkspaceScala.scala:62)
 at org.nlogo.agent.ImporterJ.showError(ImporterJ.java:1255)
 at org.nlogo.agent.ImporterJ.importWorld(ImporterJ.java:173)
 at org.nlogo.agent.World2D.importWorld(World.scala:190)
 at org.nlogo.workspace.AbstractWorkspace.importWorld(AbstractWorkspace.java:304)
 at org.nlogo.window.GUIWorkspace.importWorld(GUIWorkspace.java:190)
 at org.nlogo.extension.importa.ImportExtension$WorldPrim$.perform(ImportExtension.scala:54)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.4.0
main: org.nlogo.app.AppFrame
thread: JobThread
OpenJDK 64-Bit Server VM 17.0.8.1 (BellSoft; 17.0.8.1+1-LTS)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.18
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: snake_game

12:21:48.825 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
12:21:48.809 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:21:48.805 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
12:21:48.803 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:21:48.796 TickStateChangeEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) JobThread
12:21:48.793 OutputEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
12:21:48.792 AddJobEvent (org.nlogo.window.ButtonWidget) AWT-EventQueue-0
12:21:48.769 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:21:48.769 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0
12:21:48.769 InterfaceGlobalEvent (org.nlogo.window.ChooserWidget) AWT-EventQueue-0

**Comment by brandesNW** [comment]
Hi,
We are sorry you encountered this problem.
In order for us to help you we need instructions on how to reproduce the problem. It would help if you send us a NetLogo model (ideally not too complex) and instructions for how to reproduce the issue.

Because Github does not accept files with the extension .nlogo if you do send a model either 1) send it inside a zip file, or 2) change the name to have an acceptable extension such as .txt.

**Comment by YahyaGamal** [comment]
I am experiencing a similar error (copied at the end of this comment). In my case, loading an exported world through `import-a:world` coupled with `fetch:url` led to the issue when using the NetLogo local app. This error happens after loading the imported world's agents and their parameters into NetLogo. So, for my implementation (shown in detail below with attached files) the model would function properly after the error is displayed as long as I manually execute the required function because the error stops NetLogo from executing a sequence of commands.

For replicating the process, I am attaching the following:
1. A NetLogo file with the `setup` button importing worlds from this [online repository](https://github.com/YahyaGamal/Simplified-Housing-ABM). Please modify the extension to .nlogo to open the file properly. [[ABM_import-a_error.txt](https://github.com/user-attachments/files/17258800/ABM_import-a_error.txt)]
2. The world file that leads to the error (error world) [[S19.0.16_world_300years_3monthsTick_error.csv](https://github.com/user-attachments/files/17258795/S19.0.16_world_300years_3monthsTick_error.csv)]
3. The world file that does not lead to the error (clean world) [[S19.0.16_world_300years_3monthsTick_clean.csv](https://github.com/user-attachments/files/17258798/S19.0.16_world_300years_3monthsTick_clean.csv)]


To import the "error world" using `import-a:world` from a URL, open the NetLogo file and set the `Baseline-type` input as `"3-month step (ERROR)"` then press the `Setup` button. This will import all the agents and their parameters, but it will not create any drawn lines. At this state, I re-exported the world and labelled it as "clean world". Interestingly, loading the exported "clean world" through setting the `Baseline-type` input as `"3-month step"` does not lead to any errors. 

As I mentioned previously, the key difference that I can observe between the "error world" and the "clean world" is that the former includes information about the required lines to draw (which I assume is causing the error). I may be missing something here, but I thought reporting the error alongside my observations can be useful.

Here is the error:


```
NetLogo is unable to supply you with more details about this error.  Please report the problem 
 at https://github.com/NetLogo/NetLogo/issues, or to bugs@ccl.northwestern.edu, and paste the 
contents of this window into your report. 


java.lang.IllegalArgumentException: requirement failed: not event thread: Thread[JobThread,4,main]
 at scala.Predef$.require(Predef.scala:281)
 at org.nlogo.awt.EventQueue$.mustBeEventDispatchThread(EventQueue.scala:23)
 at org.nlogo.awt.EventQueue.mustBeEventDispatchThread(EventQueue.scala)
 at org.nlogo.window.GUIWorkspace.resizeView(GUIWorkspace.java:328)
 at org.nlogo.agent.ImporterJ.importDrawing(ImporterJ.java:205)
 at org.nlogo.agent.ImporterJ.importWorld(ImporterJ.java:160)
 at org.nlogo.agent.World2D.importWorld(World.scala:191)
 at org.nlogo.workspace.AbstractWorkspace.importWorld(AbstractWorkspace.java:281)
 at org.nlogo.window.GUIWorkspace.importWorld(GUIWorkspace.java:191)
 at org.nlogo.extension.importa.ImportExtension$WorldPrim$.perform(ImportExtension.scala:54)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.runExclusive(Context.java:133)
 at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:175)
 at org.nlogo.nvm.AnonymousCommand.perform(AnonymousProcedure.scala:157)
 at org.nlogo.extension.fetch.FetchExtension$URLAsyncPrim$.perform(FetchExtension.scala:67)
 at org.nlogo.prim._extern.perform(_extern.java:36)
 at org.nlogo.nvm.Context.stepConcurrent(Context.java:107)
 at org.nlogo.nvm.ConcurrentJob.step(ConcurrentJob.scala:65)
 at org.nlogo.job.JobThread.runPrimaryJobs(JobThread.scala:133)
 at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:68)
 at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
 at scala.util.control.Exception$Catch.apply(Exception.scala:228)
 at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
 at org.nlogo.job.JobThread.run(JobThread.scala:66)

NetLogo 6.1.0
main: org.nlogo.app.AppFrame
thread: JobThread
Java HotSpot(TM) 64-Bit Server VM 1.8.0_202 (Oracle Corporation; 1.8.0_202-b08)
operating system: Windows 10 10.0 (amd64 processor)
Scala version 2.12.8
JOGL: (3D View not initialized)
OpenGL Graphics: (3D View not initialized)
model: ABM_import-a_error

01:50:22.545 SwitchedTabsEvent (org.nlogo.app.Tabs) AWT-EventQueue-0
01:50:22.534 RuntimeErrorEvent (org.nlogo.app.App$$anon$4 (org.nlogo.window.GUIWorkspace)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
01:50:22.534 InterfaceGlobalEvent (org.nlogo.widget.SwitchWidget) AWT-EventQueue-0
01:50:22.533 InterfaceGlobalEvent (org.nlogo.window.InputBoxWidget) AWT-EventQueue-0
01:50:22.533 InterfaceGlobalEvent (org.nlogo.app.interfacetab.InterfacePanel$$anon$1 (org.nlogo.window.SliderWidget)) AWT-EventQueue-0
```
